version: '3.8'
services:
  food-delivery-db:
    image: mysql:8
    container_name: food-delivery-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootcamp_capstone_db
    ports:
      - 3307:3306
    restart: always

  food-delivery-angular:
    build: ./frontendAngular/foodDelivery/my
    container_name: food-delivery-angular
    ports:
      - 80:80
    restart: always 

  eureka-server:
    build: ./backendMicroservice/EurekaServer/
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  food-delivery-microservice:
    build: ./backendMicroservice/FoodDeliveryMicroservice/
    ports:
      - 8282:8282
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=food-delivery-microservice 
    depends_on:
      - food-delivery-db
      - eureka-server
    restart: always

volumes:
  db:
   driver: local 

   