export enum DishType {
    SALAD = "FROM THE GARDEN",
    PIZZA = "WOOD FIRED PIZZAS",
    PASTA = "DELICIOUS PASTAS",
    SPECIALS = "SPECIALS",
    BURGERS = "BETWEEN THE SLICES",
    DESSERT = "DESSERTS"
}
